### PR TITLE
Fix wrap-not-modified middleware

### LINKED ISSUE #322: Match HTTP caching spec when an ETag and If-Modified-Since are both provided
The [HTTP spec](http://www.rfcreader.com/#rfc2616_line4081) says:

> An HTTP/1.1 origin server, upon receiving a conditional request that includes both a Last-Modified date (e.g., in an If-Modified-Since or If-Unmodified-Since header field) and one or more entity tags (e.g., in an If-Match, If-None-Match, or If-Range header field) as cache validators, MUST NOT return a response status of 304 (Not Modified) unless doing so is consistent with all of the conditional header fields in the request.

I think there is a bug in the way the Ring not-modified middleware determines when to send a 304. If an If-None-Match (ETag) _or_ If-Modified-Since (Last-Modified) header is provided, then it works correctly. However if the client provides both, then the Ring middleware will return a 304 if either match, even though the HTTP spec says that all conditional header fields should match.

https://github.com/ring-clojure/ring/blob/7cada1b1723b3df996de794ad70edb0286e78455/ring-core/src/ring/middleware/not_modified.clj#L29-L39

See also https://stackoverflow.com/questions/824152/what-takes-precedence-the-etag-or-last-modified-http-header/1560098.

### PR DESCRIPTION
**Pull request by danielcompton**
Correctly return 200 when both date and etag validators are provided but only one matches.

Another approach to the checking logic is pattern matching on a `case`:

```clj
(case [(some? modified-since) (some? if-none-match)]
  [true true] (and (etag-match? request response)
                   (not-modified-since? request response))
  [true false] (not-modified-since? request response)
  [false true] (etag-match? request response)
  [false false] false)
```

Not sure which you prefer (or another approach?).

Fixes #322

### CODE REVIEW

File: ring-core/src/ring/middleware/not_modified.clj [hunk 1]
```diff
@@ -26,15 +26,26 @@
 (defn- ok-response? [response]
   (= (:status response) 200))
 
+(defn- validators-match?
+  "Checks if all provided cache validators match against the current
```
Comment (weavejester) [inline ring-core/src/ring/middleware/not_modified.clj]: Can you remove the docstring? It's a private function so it's unnecessary.

File: ring-core/src/ring/middleware/not_modified.clj [hunk 2]
```diff
@@ -26,15 +26,26 @@
...
+  cache validators."
+  [request response]
+  (let [modified-since (get-header request "if-modified-since")
+        if-none-match (get-header request "if-none-match")]
```
Comment (weavejester) [inline ring-core/src/ring/middleware/not_modified.clj]: Can you align the `let` clauses?

File: ring-core/src/ring/middleware/not_modified.clj [hunk 3]
```diff
@@ -26,15 +26,26 @@
...
+    (if (and (not (nil? modified-since)) (not (nil? if-none-match)))
```
Comment (weavejester) [inline ring-core/src/ring/middleware/not_modified.clj]: Perhaps instead:

```clojure
(and modified-since if-none-match)
```

Since we know that they can't be `false`.

File: ring-core/src/ring/middleware/not_modified.clj [hunk 4]
```diff
@@ -26,15 +26,26 @@
 (defn- ok-response? [response]
   (= (:status response) 200))
 
+(defn- validators-match?
```
Comment (weavejester) [inline ring-core/src/ring/middleware/not_modified.clj]: Can you change the function name to: `cached-response?`

**Comment by weavejester** [comment]
Thanks for the patch. I've made a few comments.

File: ring-core/src/ring/middleware/not_modified.clj (hunk 1 above)
Comment (danielcompton) [reply ring-core/src/ring/middleware/not_modified.clj]: I added the docstring to make it clearer what the intention of the code is. Do you want it as a comment, or not at all?

Comment (weavejester) [reply ring-core/src/ring/middleware/not_modified.clj]: Not at all, I think. Docstrings on private functions are (more or less) the same as comments. If you're reading them, there's a good chance you have the source code open.

Comments should, in my view, explain *why* rather than *what*. If it's not obvious *why* we've written some code, it deserves a comment to explain. On the other hand, *what* a function does should be obvious from the code; if it's not obvious, then we need to write clearer code!

File: ring-core/src/ring/middleware/not_modified.clj [hunk 5]
```diff
@@ -26,15 +26,24 @@
 (defn- ok-response? [response]
   (= (:status response) 200))
 
+(defn- cached-response?
+  [request response]
```
Comment (weavejester) [inline ring-core/src/ring/middleware/not_modified.clj]: Could you put line 29 and 30 together?

**Comment by weavejester** [comment]
Thanks! I just have one small formatting comment to address, and then can you squash your commits ready to merge? Also can you add a "." to the end of "Fixes #322".

**Comment by danielcompton** [comment]
Done.
