### PR TITLE
Prevent 2nd call of handler on unhandled exception

### LINKED ISSUE #364: Jetty adapter - handler is called a second time if unhandled exception is thrown
in the upgrade between versions `1.7.0` and `1.7.1`, `ring-jetty-adapter` upgraded its dependency on jetty from version `9.2.24.v20180105` to `9.4.12.v20180830`. as a result ring's behaviour when an unhandled exception is thrown has changed - the handler is now *called a second time* if an unhandled exception is thrown.

i've made a simple repo that reproduces the issue here: https://github.com/HealthUnlocked/ring-issue

if you run this repo and curl the endpoint, you'll see the handler logging twice, once before and once after the exception is thrown. if you change the `ring` dependencies to `1.7.0` and try the same, you'll see the logging once.

we encountered this as a result of a bug with one of our endpoints that sends an email and then tries to return an unserializable response - causing an unhandled exception. since upgrading the email gets sent twice every time the endpoint is called.

i've tried searching documentation and i can't even tell if this is intentional behaviour on jetty's part (but i can't believe that it would be?) and i realise this is not really ring's responsibility but i don't know if there's something that ring could do to protect its users from this behaviour? i will raise an issue on jetty's github as well.

### PR DESCRIPTION
**Pull request by rsslldnphy**
Since version `9.4.12.v20180830`, Jetty's `AbstractCachingHandler` calls `handle` a second time when an exception is thrown. This is so handlers can render custom error pages.

However in `ring` this would normally be done elsewhere in middleware - so this causes the normal handler to be called a second time on unhandled error, which causes a duplication of any side-effects of the handler function.

The second time `handle` is called, it's caled with a `DispatcherType` of `DispatcherType/ERROR` - so this commit checks for this `DispatcherType` and skips calling the user's ring handler in this case. This leads to a generic Jetty error page being returned.

Async handlers don't seem to be affected in the same way, so I haven't made the same change there, but I've added a test case so that if the same thing does start happening, it will be caught.

Fixes #364.

### CODE REVIEW

File: ring-jetty-adapter/test/ring/adapter/test/jetty.clj [hunk 1]
```diff
@@ -375,3 +375,27 @@
...
+
+(defn- broken-handler [request]
+  (swap! call-count inc)
+  (throw (ex-info "unhandled exception" {})))
+
+(defn- broken-handler-cps [request respond raise]
+  (swap! call-count inc)
+  (raise (ex-info "unhandled exception" {})))
+
+(testing "broken handler is only called once (see https://github.com/ring-clojure/ring/issues/364)"
```
Comment (weavejester) [inline ring-jetty-adapter/test/ring/adapter/test/jetty.clj]: We can use blame to find out the associated PR/issue. You can remove the URL.

File: ring-jetty-adapter/test/ring/adapter/test/jetty.clj [hunk 2]
```diff
@@ -375,3 +375,27 @@
...
+  (reset! call-count 0)
+  (with-server broken-handler {:port test-port}
+    (try (http/get test-url)
+      (catch Exception _ nil))
+    (is (= 1 @call-count))))
+
+(testing "broken async handler is only called once (see https://github.com/ring-clojure/ring/issues/364)"
```
Comment (weavejester) [inline ring-jetty-adapter/test/ring/adapter/test/jetty.clj]: As before, the reference to the issue can be removed.

**Comment by weavejester** [comment]
Thanks! Sorry for the delay, but Github doesn't seem to notify for changes to commits.

The commit message subject is now fine, but it looks like the rest of the commit message could use a little work. It could be more concise, needs to wrap at 72 characters, and because it's plaintext rather than markdown, backticks aren't used.

So perhaps instead:

```
Prevent 2nd call of handler on unhandled exception

Since version 9.4.12.v20180830, Jetty's AbstractCachingHandler calls
its handle method a second time when an exception is thrown. This
commit prevents Ring's handler function from being called twice as a
result of this change to Jetty.
```

**Comment by rsslldnphy** [comment]
no worries - updated

**Comment by weavejester** [comment]
Merged. Thanks for the patch!

**Comment by darkleaf** [comment]
When this patch will be released?
