### PR TITLE
Fix response streaming in case of error

### LINKED ISSUE #420: Exception handling for InputStream
Hi there,

I have a problem returning `InputStream` as body using latest Ring(1.8.2) and Jetty.
I noticed that if `InputStream` returned a few bytes and then an Exception was thrown(could happen in my case) then http-client received partial data but thinking that he received all the data.

Here is test/example of this issue
https://gist.github.com/lightZebra/56bc2f21218dbec52214fb0af9adb2b4

If I understood correctly this happened because of [with-open](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/core/protocols.clj#L35) inside `StreamableResponseBody` for InputStream.
Exception was thrown and ring closed OutputStream like streaming finished successfully and jetty couldn't finish it correctly
I didn't find in Jetty's documentation information that `Handler` should close `OutputStream`, so I tried `extend-protocol` and removed `with-open` and client received an error, like it should

I'm kinda new to ring and jetty, am I doing something wrong or it is a bug?

### PR DESCRIPTION
**Pull request by lightZebra**
OutputStream will not be closed in case of error
so underlying server could handle it properly.
Fixed issue: termination chunk was send after
streaming interruption by error.

Fixes #420.

### CODE REVIEW

File: ring-core/test/ring/core/test/protocols.clj [hunk 1]
```diff
@@ -1,7 +1,8 @@
 (ns ring.core.test.protocols
   (:require [clojure.test :refer :all]
             [clojure.java.io :as io]
-            [ring.core.protocols :refer :all]))
+            [ring.core.protocols :refer :all])
+  (:import (java.io SequenceInputStream IOException InputStream OutputStream)))
```
Comment (weavejester) [inline ring-core/test/ring/core/test/protocols.clj:5]: Can you change this to:

```clojure
(:import [java.io SequenceInputStream IOException InputStream OutputStream]))
```

File: ring-core/test/ring/core/test/protocols.clj [hunk 2]
```diff
@@ -53,3 +54,36 @@
           response {:body nil}]
       (write-body-to-stream (:body response) response output)
       (is (= "" (.toString output))))))
+
+(defn output-stream-with-close-flag []
+  (let [is-stream-closed (atom false)
```
Comment (weavejester) [inline ring-core/test/ring/core/test/protocols.clj:59]: `is-stream-closed` should be `stream-closed?` to fit in with Clojure naming schemes.

File: ring-core/test/ring/core/test/protocols.clj [hunk 3]
```diff
@@ -53,3 +54,36 @@
...
+    (read
+      ([] (throw (IOException. "test error")))
+      ([^bytes _] (throw (IOException. "test error")))
+      ([^bytes _ _ _] (throw (IOException. "test error"))))))
+
+(deftest test-error-when-writing-body
+  (testing "input streams with error"
+    (let [[output is-stream-closed] (output-stream-with-close-flag)
+          response {:body (SequenceInputStream.
+                            (io/input-stream (io/resource "ring/assets/hello world.txt"))
```
Comment (weavejester) [inline ring-core/test/ring/core/test/protocols.clj:79]: Use standard Clojure indentation.

File: ring-jetty-adapter/test/ring/adapter/test/jetty.clj [hunk 4]
```diff
@@ -10,7 +10,9 @@
            [org.eclipse.jetty.server Server Request SslConnectionFactory]
            [org.eclipse.jetty.server.handler AbstractHandler]
            [java.net ServerSocket ConnectException]
-           [java.security KeyStore]))
+           [java.security KeyStore]
+           (java.io SequenceInputStream ByteArrayInputStream InputStream IOException)
```
Comment (weavejester) [inline ring-jetty-adapter/test/ring/adapter/test/jetty.clj:14]: Please match the style of ther lines, e.g.

```clojure
[java.io SequenceInputStream ByteArrayInputStream InputStream IOException]
```

**Review by weavejester — CHANGES_REQUESTED** [review]

File: ring-core/test/ring/core/test/protocols.clj [hunk 5]
```diff
@@ -53,3 +54,36 @@
...
+    (read
+      ([] (throw (IOException. "test error")))
+      ([^bytes _] (throw (IOException. "test error")))
+      ([^bytes _ _ _] (throw (IOException. "test error"))))))
+
+(deftest test-error-when-writing-body
+  (testing "input streams with error"
+    (let [[output stream-closed?] (output-stream-with-close-flag)
+          response                {:body (SequenceInputStream.
+                                           (io/input-stream (io/resource "ring/assets/hello world.txt"))
```
Comment (weavejester) [inline ring-core/test/ring/core/test/protocols.clj:79]: Please ensure lines do not exceed 80 characters. See the contributing guidelines for more information.

File: ring-core/src/ring/core/protocols.clj [hunk 6]
```diff
@@ -19,25 +19,28 @@
...
-      (.write out ^bytes body)))
+    (.write output-stream ^bytes body)
+    (.close output-stream))
   String
   (write-body-to-stream [body response output-stream]
-    (with-open [writer (response-writer response output-stream)]
-      (.write writer body)))
+    (let [writer (response-writer response output-stream)]
+      (.write writer body)
+      (.close writer)))
```
Comment (weavejester) [inline ring-core/src/ring/core/protocols.clj:28]: For this, let's rewrite it as:

```clojure
(doto (response-writer response output-stream)
  (.write body)
  (.close))
```

File: ring-core/test/ring/core/test/protocols.clj (hunk 5 above)
Comment (lightZebra) [reply ring-core/test/ring/core/test/protocols.clj]: Changed code a little to fit in 80 characters.
Updated test/ring/adapter/test/jetty.clj to fit maximum line length.

**Comment by lightZebra** [comment]
@weavejester do we need to changes anything else?

**Comment by weavejester** [comment]
The code looks fine. Could you change the commit message to:

```
Remove closing of response stream on exception

When an exception occurs, the response output stream should not
automatically be closed, as that prevents the adapter from changing the
output of the stream to handle the exception.

Fixes #420.
```

**Comment by lightZebra** [comment]
@weavejester commit message updated

**Comment by weavejester** [comment]
Great, thanks!

**Comment by lightZebra** [comment]
Thank you
